### ISSUE TITLE
Could Not Build Wheels

### ISSUE THREAD

**Issue by Alchemyr** [BrokenShell/Fortuna#2]
![image](https://user-images.githubusercontent.com/19378093/127545889-d211fab3-80e3-481a-b9d8-a290ce30f50a.png)
Not entirely sure what to do, as I'm still new to working with stuff like this. I've included the full output upon trying to install Fortuna via pip.

**Comment by BrokenShell** [comment]
This is a great catch, thank you for posting it. What OS are you using here? I'll try to replicate the problem.

**Comment by BrokenShell** [comment]
```
sudo apt update
sudo apt install python3 python3-dev

**Comment by Alchemyr** [comment]
Oh my, sorry! I missed your first response. 

I am using Ubuntu on windows. I forget how to check the specifics for that, though.... 

I am using the newest version of Python, too.

**Comment by BrokenShell** [comment]
I think you're missing the python dev environment... see above

**Comment by Alchemyr** [comment]
Alrighty, I tried that. Got the same result.

**Comment by Alchemyr** [comment]
Quick update - this is what it said after I ran the two commands.
![image](https://user-images.githubusercontent.com/19378093/129459300-812c6739-fdab-4397-8c78-f364150e699d.png)

**Comment by Alchemyr** [comment]
Just an update - tried a fresh install of Python and Ubuntu itself. Still getting the same issue. Hmmm.

**Comment by BrokenShell** [comment]
Do you have a modern c++ compiler? Like g++

**Comment by Alchemyr** [comment]
Good question - I'm not quite sure. How would I check?

**Comment by BrokenShell** [comment]
`sudo apt install g++`

**Comment by Alchemyr** [comment]
Alright, just tried that -- same result.

**Comment by Alchemyr** [comment]
Just an update - still unable to get it to work.

**Comment by levijhall** [comment]
It seems to happen when the venv's version of Python is greater than what is running locally. The version that python3-dev is defaulting to is 3.8 in this case, but Fortuna expects dev files for 3.9.

The line `-I/usr/include/python3.9` is the culprit. Running `sudo apt-get install python3.9-dev' should resolve the issue.
